name: Android CI (APK Auto Build)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '7.5'

    - name: Generate Gradle Wrapper
      run: gradle wrapper --gradle-version 7.5

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Upload APK to Github Actions
      uses: actions/upload-artifact@v4
      with:
        name: TossAuto-APK
        path: app/build/outputs/apk/debug/app-debug.apk
